name: get geojson

on:
 workflow_call:
 workflow_dispatch:
 

jobs:
  genRank:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get BTC MAP Rank1
        id: getRank
        run: npm install -g mapshaper && curl "https://nominatim.openstreetmap.org/lookup?osm_ids=R7477259&format=json&polygon_geojson=" | jq '.[0].geojson' > input.json && mapshaper input.json -simplify 10% -o output.json && cat output.json | jq '.geometries[0]' -c > geo.json
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
            token: ${{ secrets.GIST_TOKEN }}
            gist_id: b7e8e9eda6df4fe0e4f59d75f8670fe0
            file_path: geo.json
