name: get BTCMAP rank

on:
 workflow_call:
 workflow_dispatch:
 

jobs:
  genRank:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get BTC MAP Rank1
        id: getRank
        run: npm install -g mapshaper && curl "https://nominatim.openstreetmap.org/lookup?osm_ids=R7477259&format=json&polygon_geojson=" | jq '.[0].geojson' > input.json && mapshaper input.json -simplify 10% -o output.json && cat output.json | jq '.geometries[0]' -c > geo.json
      - uses: actions/upload-artifact@v4
        with:
         name: output geojson
         path: output.json
      - name: Update/Create Gist
        uses: sindresorhus/create-gist@v3
        with:
          # REQUIRED: The token you stored as a secret in Step 1.
          token: ${{ secrets.GIST_TOKEN }} 
          
          # REQUIRED: The ID of the Gist to update. If it doesn't exist, it will be created.
          # To create a new Gist, leave this out (or set it to an empty string), 
          # but then you must use a static 'name' for the file.
          gist-id: 'geojson'
          file: geo.json
